apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api
  name: api-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - image: gcr.io/mcc-2016-g15-p2/myapp
        name: api
        ports:
        - containerPort: 8080
          name: http-server